name: yt_downloader
description: "A simple Youtube Downloader App"

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: 'launcher_icon'
  image_path: 'assets/icon.png'